[project]
name = "cflsync"
version = "0.1.0"
authors = [
    { name = "Sven Rosiers", email = "github-sro@rosiers.info" },
]
license = "MPL-2.0"
requires-python = ">=3.11"
dependencies = [
    "platformdirs>=4.3.8",
]

[dependency-groups]
dev = [
    "yapf>=0.43",
]

[tool.yapf]
based_on_style = "pep8"
blank_line_before_module_docstring = true
column_limit = 132
indent_width = 4
continuation_indent_width = 4
continuation_align_style = "SPACE"
split_before_first_argument = true
split_before_closing_bracket = false
disable_ending_comma_heuristic = true
dedent_closing_brackets = false
indent_closing_brackets = false

[tool.zuban]
python_executable = ".venv/bin/python"
